(cl:in-package cacc_msgs-msg)
(cl:export '(DS-VAL
          DS
          DMIN-VAL
          DMIN
          UMAX-VAL
          UMAX
          UMIN-VAL
          UMIN
          SF0-VAL
          SF0
          SF1-VAL
          SF1
          SF2-VAL
          SF2
          Q0-VAL
          Q0
          Q1-VAL
          Q1
          Q2-VAL
          Q2
          R-VAL
          R
          SU-VAL
          SU
          SD-VAL
          SD
          TF-VAL
          TF
          HT-VAL
          HT
          DV-VAL
          DV
          ZETA-VAL
          ZETA
          KMAX-VAL
          KMAX
))