(cl:in-package cacc_msgs-msg)
(cl:export '(ID-VAL
          ID
          MANUAL-VAL
          MANUAL
          THW-VAL
          THW
          ALPHA-VAL
          ALPHA
          BETA-VAL
          BETA
          SENSOR2FRONTBUMPER-VAL
          SENSOR2FRONTBUMPER
          SENSOR2REARBUMPER-VAL
          SENSOR2REARBUMPER
          VEL_GAIN-VAL
          VEL_GAIN
          VEL_GAIN_LOW-VAL
          VEL_GAIN_LOW
          VEL_GAIN_DEC-VAL
          VEL_GAIN_DEC
          X-VAL
          X
          Y-VAL
          Y
          U-VAL
          U
          V-VAL
          V
          YAW-VAL
          YAW
          SPEED-VAL
          SPEED
          ACCELERATION-VAL
          ACCELERATION
          FRONT_X-VAL
          FRONT_X
          FRONT_Y-VAL
          FRONT_Y
          FRONT_U-VAL
          FRONT_U
          FRONT_V-VAL
          FRONT_V
          FRONT_YAW-VAL
          FRONT_YAW
          FRONT_SPEED-VAL
          FRONT_SPEED
          FRONT_ACCELERATION-VAL
          FRONT_ACCELERATION
          FRONT_DISTANCE-VAL
          FRONT_DISTANCE
          REAR_X-VAL
          REAR_X
          REAR_Y-VAL
          REAR_Y
          REAR_U-VAL
          REAR_U
          REAR_V-VAL
          REAR_V
          REAR_YAW-VAL
          REAR_YAW
          REAR_SPEED-VAL
          REAR_SPEED
          REAR_ACCELERATION-VAL
          REAR_ACCELERATION
          REAR_DISTANCE-VAL
          REAR_DISTANCE
          CHECKSUM-VAL
          CHECKSUM
))