// Generated by gencpp from file custom_pkg/control_signal.msg
// DO NOT EDIT!


#ifndef CUSTOM_PKG_MESSAGE_CONTROL_SIGNAL_H
#define CUSTOM_PKG_MESSAGE_CONTROL_SIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_pkg
{
template <class ContainerAllocator>
struct control_signal_
{
  typedef control_signal_<ContainerAllocator> Type;

  control_signal_()
    : header()
    , accel(0.0)
    , steer(0.0)
    , status(0)  {
    }
  control_signal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , accel(0.0)
    , steer(0.0)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _accel_type;
  _accel_type accel;

   typedef float _steer_type;
  _steer_type steer;

   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::custom_pkg::control_signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_pkg::control_signal_<ContainerAllocator> const> ConstPtr;

}; // struct control_signal_

typedef ::custom_pkg::control_signal_<std::allocator<void> > control_signal;

typedef boost::shared_ptr< ::custom_pkg::control_signal > control_signalPtr;
typedef boost::shared_ptr< ::custom_pkg::control_signal const> control_signalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_pkg::control_signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_pkg::control_signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_pkg::control_signal_<ContainerAllocator1> & lhs, const ::custom_pkg::control_signal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.accel == rhs.accel &&
    lhs.steer == rhs.steer &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_pkg::control_signal_<ContainerAllocator1> & lhs, const ::custom_pkg::control_signal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_pkg::control_signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_pkg::control_signal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_pkg::control_signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_pkg::control_signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_pkg::control_signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_pkg::control_signal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_pkg::control_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da55517947a600b569ad9bc4fd50c76b";
  }

  static const char* value(const ::custom_pkg::control_signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda55517947a600b5ULL;
  static const uint64_t static_value2 = 0x69ad9bc4fd50c76bULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_pkg::control_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_pkg/control_signal";
  }

  static const char* value(const ::custom_pkg::control_signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_pkg::control_signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 accel\n"
"float32 steer\n"
"int8 status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_pkg::control_signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_pkg::control_signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.accel);
      stream.next(m.steer);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_pkg::control_signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_pkg::control_signal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "accel: ";
    Printer<float>::stream(s, indent + "  ", v.accel);
    s << indent << "steer: ";
    Printer<float>::stream(s, indent + "  ", v.steer);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_PKG_MESSAGE_CONTROL_SIGNAL_H
